version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker/development/nginx
        container_name: server
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - api
            - frontend

    frontend:
        build:
            context: frontend/docker
            dockerfile: development/nginx/Dockerfile
        container_name: frontend
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        container_name: api-server
        volumes:
            - ./api:/app
        depends_on:
          - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        container_name: api-php-fpm
        volumes:
            - ./api:/app
        environment:
            APP_ENV: dev
            APP_DEBUG: 1

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        container_name: api-php-cli
        volumes:
            - ./api:/app
        environment:
            APP_ENV: dev
            APP_DEBUG: 1

